settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-pblaze-com
    name: www.pblaze.com
    description: 'pblaze首页'
    url: 'https://www.pblaze.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: sv-gui-ink
    name: sv.gui.ink
    description: '探针'
    url: 'https://sv.gui.ink/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: mail-pblaze-com
    name: mail.pblaze.com
    description: 'pblaze 邮箱'
    url: 'https://mail.pblaze.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
