settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
- id: www-pblaze-com
  name: www.pblaze.com
  url: 'https://www.pblaze.com/'
  method: GET
  expectStatus: 200

- id: sv-gui-ink
  name: sv.gui.ink
  url: 'https://sv.gui.ink/'
  method: GET
  expectStatus: 200

- id: www-2k2-cc
  name: www.2k2.cc
  url: 'https://www.2k2.cc/'
  method: GET
  expectStatus: 200

- id: x-kalijerry-uk
  name: x.kalijerry.uk
  url: 'https://x.kalijerry.uk/'
  method: GET
  expectStatus: 200
